### PR TITLE
Adding new cache - osg-stash-sfu-computecanada-ca.nationalresearchplatform.org - default branch

### PR DESCRIPTION
**Pull request by biozit**
We have a new Canada cache: osg-stash-sfu-computecanada-ca.nationalresearchplatform.org

### CODE REVIEW

**Review by DrDaveD — CHANGES_REQUESTED** [review]
This should instead be added on the next line where it says "stashcache servers not configured by OSG".

**Comment by DrDaveD** [comment]
@biozit Don't forget to update this similarly to the way you did for the egi branch (except not for ligo).

**Comment by biozit** [comment]
done

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
I'm going to go ahead and merge this, since I know that there's another cache coming right away and @jblomer can wait to distribute until that one is also in.

**Pull request merged**
