### PR TITLE
update Korea cache - egi

### PR DESCRIPTION
**Pull request by biozit**

### CODE REVIEW

**Review by DrDaveD — APPROVED** [review]
This just substitutes an alias for the same machine.

@jose-caballero I'll leave it to you to merge and distribute.

**Review by DrDaveD — CHANGES_REQUESTED** [review]
Wait.  The corresponding change to osgstorage.org.conf is missng.

**Review by DrDaveD — APPROVED** [review]
Ok, ready to go for egi.

**Comment by jose-caballero** [comment]
Hi,
I have approved the merge. 

However, I would like to say I don't like doing it when there is no explanation in the commit message. It should explain clearly what is being done and why.

**Comment by biozit** [comment]
I changed the certs from this cache, and it requires changing the hostname

**Pull request merged**
