### PR TITLE
set stashcache.gravity.cf.ac.uk to port 8443

### PR DESCRIPTION
**Pull request by biozit**

### CODE REVIEW

**Comment by brianhlin** [comment]
From https://github.com/opensciencegrid/topology/actions/runs/3238833319/jobs/5307493604#step:4:26

**Comment by DrDaveD** [comment]
I'm seeing no response to a telnet connection to port 8443.  On the other hand, port 8444 is getting connection refused.  Can somebody contact the admin?

**Comment by biozit** [comment]
I am checking

**Comment by biozit** [comment]
It looks like the node has a firewall; we are checking it.

**Comment by DrDaveD** [comment]
Superceded by #123

**Pull request closed without merging**
