### PR TITLE
adding https://kagra-dsr-b1.icrr.u-tokyo.ac.jp:8443/" (osg)

### PR DESCRIPTION
**Pull request by biozit**
adding https://kagra-dsr-b1.icrr.u-tokyo.ac.jp:8443/"

### CODE REVIEW

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
For @jthiltges to merge and deploy

**Comment by biozit** [comment]
@DrDaveD, it is only the OSDF auth instance.

**Comment by DrDaveD** [comment]
Right, I saw that message and that's why I approved this PR.

**Comment by jthiltges** [comment]
Change published in revision 135.

**Pull request merged**
