### PR TITLE
Adding cache to EGI

### PR DESCRIPTION
**Pull request by biozit**
Adding new OSDF caches to EGI. We have new caches on US and Europe

### CODE REVIEW

**Comment by DrDaveD** [comment]
Related to #181.  For @jose-caballero to approve, merge, and deploy.

**Review by jose-caballero — CHANGES_REQUESTED** [review]
Please, add an explanation of why this change is needed to the commit message.

**Comment by biozit** [comment]
@jose-caballero I added the reason on the commit message. I added all the available caches on the master branch.

**Comment by DrDaveD** [comment]
Oh, @biozit please add back the newline on the end of etc/cvmfs/domain.d/osgstorage.org.conf

**Comment by biozit** [comment]
done

**Comment by bbockelm** [comment]
@jose-caballero -- did you get a chance to take a look at the revised commit message?  Would be useful to get these new caches in action!

**Comment by jose-caballero** [comment]
sorry. Stuck in a Conference...

**Review by jose-caballero — APPROVED** [review]

**Pull request merged**
