### PR TITLE
Change cern to nikhef in opensciencegrid.org server list

### PR DESCRIPTION
**Pull request by DrDaveD**
Also use the cvmfs-egi alias at RAL like the other config repos do.

### CODE REVIEW

**Review by jthiltges — APPROVED** [review]
LGTM

I poked at `.cvmfspublished` for a few repos on the Nikhef hosts, and all looked fine.

**Comment by jthiltges** [comment]
@DrDaveD If it's OK with you, I'll plan to work on deploying this on Tuesday.

**Comment by DrDaveD** [comment]
Yes, sounds good.

**Comment by jthiltges** [comment]
Testing with s1nikhef-cvmfs.openhtc.io and klei.nikhef.nl looked fine. Put into production.

**Pull request merged**
