### PR TITLE
Add ligo.hpc.swin.edu.au

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Comment by djw8605** [comment]
Waiting on confirmation from admin that this is the right host.  It's not responding from external IPs (at least from my tests)

**Comment by DrDaveD** [comment]
I think you probably just need to change it port 8443.

**Comment by djw8605** [comment]
Yup, you are right.  But now the cert seems expired.  I'll provide feedback to the site.

**Comment by djw8605** [comment]
@DrDaveD could you review and shepard this change wherever it needs to go?

**Comment by DrDaveD** [comment]
You have confirmed now that it works?

**Comment by djw8605** [comment]
Yup, works.

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
Since @zvada is traveling this week I'll go ahead and deploy this.  We should also add this to the egi branch in case people in Australia use the egi configuration, and it should go into master as well.  Each one has to be a separate PR because this part of the config is different in each.  @djw8605 please go ahead and create those PRs as well.

**Pull request merged**
