### PR TITLE
reduce warnings/failures for sft-nightlies repo

### PR DESCRIPTION
**Pull request by rptaylor**
See https://github.com/cvmfs-contrib/config-repo/pull/212

### CODE REVIEW

**Comment by rptaylor** [comment]
@jblomer what do you think?

**Comment by DrDaveD** [comment]
Maybe @vvolkl could review instead.

**Comment by jblomer** [comment]
Apologies for the delay! Looks good to me.

**Review by jblomer — APPROVED** [review]

**Comment by rptaylor** [comment]
Thanks for the merge @jblomer. It looks like this hasn't been published to the config repo yet though. @vvolkl ?
```
$ ls -l /cvmfs/cvmfs-config.cern.ch/etc/cvmfs/config.d/
total 5
-rw-r--r--. 1 cvmfs cvmfs 684 Oct 12 07:18 alice.cern.ch.conf
-rw-r--r--. 1 cvmfs cvmfs 282 Sep 15  2020 atlas-nightlies.cern.ch.conf
-rw-r--r--. 1 cvmfs cvmfs 279 Sep 15  2020 cernvm-devel.cern.ch.conf
-rw-r--r--. 1 cvmfs cvmfs 277 Sep 15  2020 cernvm-sl7.cern.ch.conf
-rw-r--r--. 1 cvmfs cvmfs 278 Sep 15  2020 cernvm-slc4.cern.ch.conf
-rw-r--r--. 1 cvmfs cvmfs 278 Sep 15  2020 cernvm-slc5.cern.ch.conf
-rw-r--r--. 1 cvmfs cvmfs  22 Sep 15  2020 cms.cern.ch.conf
-rw-r--r--. 1 cvmfs cvmfs  47 Sep 15  2020 grid.cern.ch.conf
-rw-r--r--. 1 cvmfs cvmfs 323 Sep 14  2022 restricted.computecanada.ca.conf
```
That is File Catalog Revision: 26

**Comment by rptaylor** [comment]
However based on https://cvmfs-monitor-frontend.web.cern.ch/cvmfs-config.cern.ch  there was a transaction published at the time this was merged.

**Comment by jblomer** [comment]
Apologies, it has been rolled out to testing only. It is now available in the production branch of the cvmfs-config repository.

**Pull request merged**
