### PR TITLE
computecanada: remove east, add graham

### PR DESCRIPTION
**Pull request by rptaylor**
The east s1 has been decommissioned but a new one cvmfs-s1-graham.computecanada.ca has been added.

@vvolkl

### CODE REVIEW

**Comment by rptaylor** [comment]
@vvolkl @DrDaveD I noticed the master branch was out of date in the sense that it did not get https://github.com/cvmfs-contrib/config-repo/pull/115 applied. Is the master branch used for anything? As I understand only default is published to the config repo.

**Comment by DrDaveD** [comment]
> @vvolkl @DrDaveD I noticed the master branch was out of date in the sense that it did not get #115 applied. Is the master branch used for anything? As I understand only default is published to the config repo.

The master branch is intended to have a superset of everything in the other branches, so it should get there.  Please submit a PR to include those changes.  

You are correct that only the default branch is published to cvmfs-config.cern.ch.  The master branch is not used to generate any configuration repository but it is used for diffs and for downloading keys to stratum 1s.

**Comment by rptaylor** [comment]
Okay. Can this be merged now? The old stratum server has been retired so it is not reachable by clients anymore.

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
@vvolkl @jblomer this is for you to merge and deploy

**Comment by vvolkl** [comment]
Now deployed to TESTING. Will publish in production on Monday.

**Comment by rptaylor** [comment]
Thanks @vvolkl .  Looks like the prod version still has the east stratum server.

I don't recall how to use the test version of the config repo but in any case we published these changes to production awhile ago.

**Pull request merged**
