### PR TITLE
Adding the PIC stashcache host

### PR DESCRIPTION
**Pull request by efajardo**

### CODE REVIEW

**Comment by efajardo** [comment]
@zvada and @iancollier could you please review this?

**Comment by DrDaveD** [comment]
Are you sure you branched off the right branch?  There's way too many commits showing up in this PR.

**Comment by efajardo** [comment]
Well I created my own EGI branch probably that is why.

**Comment by DrDaveD** [comment]
Did you create it with `git checkout -b egi upstream/egi`?

**Comment by efajardo** [comment]
nop I did,

`git checkout -b egi`

Should I make a new PR?

**Comment by DrDaveD** [comment]
You can either make a new PR or do a git push -f to overwrite it.

**Comment by efajardo** [comment]
@DrDaveD I created new [PR-16](https://github.com/cvmfs-contrib/config-repo/pull/16). So I am closing this one.

**Pull request closed without merging**
