### PR TITLE
Adding ligo and shared storage.igwn.org configurations

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Review by DrDaveD — APPROVED** [review]
LGTM.  I'll leave to @jthiltges to merge and deploy.

**Comment by DrDaveD** [comment]
@djw8605 Please make cherry-pick PRs for master and egi branches as well.

**Comment by jthiltges** [comment]
Testing looks fine. Deployed to production.

**Comment by stuartthebruce** [comment]
I can confirm this is working for a few random CVMFS clients to read a LIGO proprietary data file from the LIGO hosted OSDF Origin `origin-ifo.ligo.caltech.edu` via `/cvmfs/ligo.storage.igwn.org` if and only if an appropriately scoped SciToken is available. Many thanks on getting to this major milestone.

**Pull request merged**
