### PR TITLE
Add cf-ac-uk-cache.nationalresearchplatform.org cache - EGI branch

### PR DESCRIPTION
**Pull request by biozit**
Add cf-ac-uk-cache.nationalresearchplatform.org

### CODE REVIEW

**Review by DrDaveD — CHANGES_REQUESTED** [review]
It looks pretty good, except please make it one commit instead of two.

**Comment by DrDaveD** [comment]
Oh and you should probably wait for your previous egi branch PR to be merged, because at that point there will be a merge conflict and you will need to rebase.

**Comment by biozit** [comment]
I have another cache to add. Should I wait for the previous merges?

**Comment by DrDaveD** [comment]
Yes, especially if you're touching the same line in the same branch.  You can also combine more than one cache in the same PR.

**Comment by biozit** [comment]
Rebased!

**Comment by DrDaveD** [comment]
For @jose-caballero to merge and distribute.

**Review by jose-caballero — APPROVED** [review]

**Pull request merged**
