### PR TITLE
Adding new cache - osg-stash-sfu-computecanada-ca.nationalresearchplatform.org - egi branch 

### PR DESCRIPTION
**Pull request by biozit**
We have a new Canada cache: osg-stash-sfu-computecanada-ca.nationalresearchplatform.org

### CODE REVIEW

**Comment by DrDaveD** [comment]
Oh and this should instead be added to the next line where it says "stashcache servers not configured by OSG".

**Comment by biozit** [comment]
> Oh and this should instead be added to the next line where it says "stashcache servers not configured by OSG".

why?

**Comment by DrDaveD** [comment]
> > Oh and this should instead be added to the next line where it says "stashcache servers not configured by OSG".
> 
> why?

Oh I guess the comment is a little misleading.  It means that it's not configured in the osg branch.

**Comment by biozit** [comment]
done

**Review by DrDaveD — CHANGES_REQUESTED** [review]
The changes look good now, but please squash them down to one commit that says "Add osg-stash-sfu-computecanada-ca" or some variant of that, describing what's changed.

**Comment by biozit** [comment]
done

**Review by DrDaveD — CHANGES_REQUESTED** [review]
It is in one commit now, but the commit message is a mess.  Please simplify it.

**Comment by biozit** [comment]
done

**Review by DrDaveD — CHANGES_REQUESTED** [review]
I'm sorry to be such a stickler, but it's still not accurate.  The first line is too generic, and the second line only applies to ligo.  It's important for the first line to be descriptive.  Extra lines are optional if they add more explanation.  So just replace both lines with something like `Add osg-stash-sfu-computecanada-ca`.

**Comment by jose-caballero** [comment]
https://cbea.ms/git-commit/

**Comment by biozit** [comment]
No problem, please. Could you check if it is ok?

*--Fábio Andrijauskas*

**Review by DrDaveD — CHANGES_REQUESTED** [review]
Unfortunately it is still not ok, because now the first line has `Adding new cache - osg branch` which is not only incorrect since it is the egi branch, it is too generic.  The second line is good; just use the second line as the first line.  You don't need to mention the branch name in the commit, because that's obvious from where it is.  It's good to have the branch name in the PR title, as you did.

**Comment by biozit** [comment]
np, done.

*--Fábio Andrijauskas*

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
Ok for @jose-caballero to merge & deploy.

@biozit Also please cherry-pick this to the master branch.

**Review by jose-caballero — APPROVED** [review]

**Pull request merged**
