### PR TITLE
Add CNAF StashCache to EGI config

### PR DESCRIPTION
**Pull request by zvada**

### CODE REVIEW

**Comment by zvada** [comment]
> Looks good to me. Let's however wait for someone from [cvmfs-support@gridpp.rl.ac.uk](mailto:cvmfs-support@gridpp.rl.ac.uk) to also approve.

yes, was in the midway of opening GGUS ticket and pointing them to review. I'd ask who can be assigned as reviewer that we have git user name as reference for the next time, too.

**Comment by zvada** [comment]
@iancollier: Do you have a possibility to merge this, too? I don't seem to be in the authorized users list to do so. @DrDaveD, should I be authorized for merging or this is meant to be for EGI reps only. Thanks.

**Comment by iancollier** [comment]
As I said in the ticket yesterday, I did not have permission to merge, but I do now. Merged. And applied to the stratum 0 at RAL.

**Comment by zvada** [comment]
> As I said in the ticket yesterday, I did not have permission to merge, but I do now. Merged. And applied to the stratum 0 at RAL.

Thanks a lot!

**Pull request merged**
