### PR TITLE
Update ga tech cache

### PR DESCRIPTION
**Pull request by efajardo**

### CODE REVIEW

**Comment by efajardo** [comment]
@zvada can you please review this and apply it?

**Comment by DrDaveD** [comment]
It looks OK to me.  It's unfortunate that they would make us change such a trivial name though, instead of them using the old name as a CNAME DNS alias for the new one.

**Comment by efajardo** [comment]
Hi @DrDaveD ,

This is not just a name change. It is a whole new beefier machine. But I guess we could have done a DNS swap or something.

**Comment by DrDaveD** [comment]
@zvada this is waiting on you

**Pull request merged**
