### PR TITLE
Set cache offline and update FQDN - EGI branch

### PR DESCRIPTION
**Pull request by biozit**
Removing due to maintenance: xcache.cr.cnaf.infn.it and stashcache.gravity.cf.ac.uk

Updating the Korea cache name: daejeon-kreonet-net.nationalresearchplatform.org

### CODE REVIEW

**Review by DrDaveD — APPROVED** [review]
Approved, although the references to korea cache in the title and description aren't relevant.  Fabio told me these caches will be in maintenance at least two weeks so it is worth taking them out of the config for now.  I leave it to @jose-caballero to merge & deploy.

**Comment by jose-caballero** [comment]
@biozit Do you have confirmation the StashCache server at Cardiff is gone?

**Comment by biozit** [comment]
@jose-caballero It is temporary to fix the cert.

**Comment by DrDaveD** [comment]
But it is expected to be at least a couple of weeks so it is worth removing.  @biozit will submit another PR when it is operational again.

**Comment by jose-caballero** [comment]
I see. The commit message was not clear. A commit message must explain explicitly and clearly what it is being changed and why.

**Pull request merged**
